### ISSUE TITLE
[CORS] No 'Access-Control-Allow-Origin' header is present on the requested resource

### ISSUE THREAD

**Issue by csells** [liyasthomas/postwoman#2]
**Describe the bug**
The following curl command works:

curl 'https://donjon.bin.sh/name/rpc.cgi?type=Party&n=10'

the equivalent command in postwoman doesn't work:

![image](https://user-images.githubusercontent.com/2568253/63511918-148f5b80-c4a8-11e9-9b4a-0384a3a2e106.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version 76

**Comment by csells** [comment]
BTW, the curl command also works on plain http:// but postwoman doesn't work with a http:// URL either.

**Comment by AndrewBastin** [comment]
Umm, well its a restriction due to the CORS (Cross Origin Request Policy), there isn't a client side work around to this unless the host your trying to access should respond with the appropriate CORS headers...

More info on CORS : [https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)

If you really want to circumvent the CORS policies and use Postwoman you can do with Browser extensions which do so, but hey, CORS policies are a security feature hence, overriding it ain't exactly safe...


As I said there isn't like a client-side (using the browser only) way to circumvent this without extensions, although I am pretty sure you could like tunnel the request through a server hosted on the same origin (or passes the CORS headers) and make it work.

Although, anyways, I will working on a PR which routes any request failing the CORS checks through tunneling servers (something like [this](https://cors-anywhere.herokuapp.com/) or [this](https://corsproxy.github.io/)) but they come with their own restrictions (like what to do about headers for example) and stability issues.

**Comment by abraham** [comment]
With #15 there is now an error displayed when CORS blocks requests.

**Comment by shmurf** [comment]
There are browser plugins that you can use to get around the CORS issue but beware, CORS is there for a reason, only use the plugin when debugging or using a site like this
Here is one such plugin
https://chrome.google.com/webstore/detail/moesif-orign-cors-changer/digfbfaphojjndkpccljibejjbppifbc?hl=en-US

**Comment by AndrewBastin** [comment]
Assigning the issue to myself as I intend to resolve it by introducing a proxy system.

**Comment by liyasthomas** [comment]
Middleware implementation has out of the box support in Nuxt.

**Comment by AndrewBastin** [comment]
Umm, I am working on this, but I have some personal stuff coming up, so I will be focusing on that for a while (a week or so).

I am unassigning myself from this meanwhile, feel free to tackle this issue if you want.

**Comment by philBrown** [comment]
Given the number of questions on StackOverflow that are some form of duplicate of [Why does my JavaScript code get a “No 'Access-Control-Allow-Origin' header is present on the requested resource” error when Postman does not?](https://stackoverflow.com/questions/20035101/why-does-my-javascript-code-get-a-no-access-control-allow-origin-header-is-pr), I don't see this as a bad thing.
