### ISSUE TITLE
Label doesn't change when switching between collection requests

### ISSUE THREAD

**Issue by lolcoolkat** [liyasthomas/postwoman#291]
Using **https://postwoman.io**:

1) Create a request, and enter in a label for your request. Then; save it in a collection
2) Create another request with a different label, and save it to a collection as well.
3) Switch between the 2 requests you made from the collections box, and the label won't change/get updated!

**Comment by liyasthomas** [comment]
@lolcoolkati
There are two labels for a request.
1. In request section. This is used for History entery.
2. In Save request. This is used for naming requests in Collection.

This allows us to create and identify same labels within a Collection or across History entries.

Both labels are binded to the current state of the request. And won't change even if use another History entry or request from a Collection.

I implemented this as a feature. Because while working with APIs, I find it's more appealing to not change previous labels for the new one unless I manually do that. This enabled me to quickly sort and group History entries (history entries can be sorted alphabetically with Label name) with its label.

If if switch between two requests, either from History or Collection, the current label won't change unless I manually do that.

Anyway, I'm open for suggestions, I can bind label to request but I personally find it not beneficial. I wanna hear how you would like to make use of labels and your expected flow of labels 😊

**Comment by lolcoolkat** [comment]
@liyasthomas it's just kinda weird that for example.. when I want to run my `Register` request from a collection.. the label says `Login`. 

![img](https://i.imgur.com/avDj3Dy.png)

Again.. it's showing `Login` after I clicked the `Register` request I saved in my collection :/

**Comment by liyasthomas** [comment]
😅 lol. That's terrific.
What I had in mind while implementing labels is something like GitHub issue/PR labels works.

1. I created an issue
2. I add labels
3. I edit my issue
4. Labels doesn't change unless I do that manually 💁
5. I could find/sort/group issues based on labels

I'll reconsider the labels workflow.
