### ISSUE TITLE
File/binary request body support 

### ISSUE THREAD

**Issue by yntelectual** [liyasthomas/postwoman#298]
First of all - thanks for the work on this cool project. 

**Describe the solution you'd like**
In order to post file content as request body, it would be comfortable to add a simple button(next to 'raw request data', or maybe as another tab) to load file from disk to sent as request body

**Describe alternatives you've considered**
Its possible to specify request body by pasting in file contents, but its cumbersome for binary files.

**Additional context**
A nice addition would be to automatically set content-type based on file extension.

**Comment by liyasthomas** [comment]
That's a cool suggestion! Will consider it.

**Comment by liyasthomas** [comment]
@yntelectual Upload payload feature is now live 🎉
On `POST` request method, there'll be an "attach file" button. Click that to upload files (JSON, XML etc..) from PC. And just "Send"! payload will posted.

**Comment by yntelectual** [comment]
Awesome! :1st_place_medal: That might have been the fastest feature request completion I have ever seen. 

One remark though:  When posting binary data, it is usually not practical to show the actual payload byte content in the raw input field. At least if the file is not textual( `.json|yamletc...`) otherwise you get massive bloat in the UI, without much benefit to the user(try uploading a jpeg for instance), plus the whole page perf suffers. 
My suggestion would be to just show file name from the file upload event in the box, sth like `Binary file: my_path.jpeg`  Or at least make the input collapsed by default if file upload was used.
![image](https://user-images.githubusercontent.com/1354787/68851953-28c5ac00-06d7-11ea-863d-1bb583bb443d.png)
Thanks again and I will try to think about other suggestions :)

**Comment by liyasthomas** [comment]
Yeah, i too had this issue. I'm working on it. Will probably fix it today itself.

**Comment by liyasthomas** [comment]
These changes were introduced last night 🎉

- Payload textarea will be collapsed by default (can be expanded as we want by dragging at the corner). This solves the long textarea for hoge payload.
- Regarding not showing the payload at all: Well, what if the user want to make a tiny change before sending, user would've to go and edit the raw file to do that, which sucks. So payload should (and will) be shown so that it could be edited.
- The above feature introduces abrupt UI while uploading binary and files except (JSON,HTML,XML,YAML etc..). Well, this could be solved by restricting upload file types to known/supported extensions. But there's this problem that on `POST`, there's support for almost all file type :/

Anyway, will figure out a workaround for that too 👍

**Comment by pengerArray** [comment]
which version will support it

**Comment by liyasthomas** [comment]
On v2

There will be form data support too✨

**Comment by semkeijsper** [comment]
Hello, I can only find the upload files button and that seems to use --data-binary.
How do you reference a file (or multiple files) with form-data?
![image](https://user-images.githubusercontent.com/78076164/106473868-96a8ef80-64a4-11eb-96e6-fe156bdcd6fb.png)
Similar to this feature in Postman.

Thank you in advance

**Comment by liyasthomas** [comment]
Referencing multiple files with a name is not implemented. We're working on this feature in current sprint. Hopefully it'll be out in couple of days.
