### ISSUE TITLE
⏬ Import a Postman's Collection

### ISSUE THREAD

**Issue by FMGordillo** [liyasthomas/postwoman#333]
**Is your feature request related to a problem? Please describe.**
[Auth0.com](https://auth0.com) offers a "Try with Postman" button that gives you a Collection of different APIs, but the schema of the output JSON is different from the one that Postwoman needs.

**Describe the solution you'd like**
An embedded transformer from Postman's Collection to Postwoman's Collection

Current Postman's schema:

```
{
  "id": "...",
  "name": "Auth0 Authentication API",
  "description": "....",
  "auth": null,
  "events": null,
  "variables": [...],
  "order": [...],
  "folders_order": [... ],
  "folders": [...],
  "requests": [...]
}
```

Current Postwoman's Schema:

```
[
  {
    "name": "My Collection",
    "folders": [],
    "requests": []
  }
]
```

**Comment by FMGordillo** [comment]
And when I try to insert my collection, the console error is: `Uncaught TypeError: Invalid attempt to spread non-iterable instance`

**Comment by liyasthomas** [comment]
I haven't look deep into it. But it seems like Postwoman does follow the same export format. Except the sample collection file. PW have provision for multiple Collections export as JSON array.

Try a sample collection export with multiple connection on Postwoman. It would be similar to this:
```
[
  {
    "name": "My Collection",
    "folders": [],
    "requests": []
  },
  {
    "name": "Hh",
    "folders": [],
    "requests": []
  }
]
```

The above export contains 2 Collections and is in array. Try multiple Collections export in PM and check it solves the import issue.

**Comment by sheldon-markk** [comment]
How to we import a postman collection? is there a way to do this?

**Comment by AdityaAnand1** [comment]
Just saw this, I tried to import postman collection here:
![image](https://user-images.githubusercontent.com/13274079/73119040-789bdb80-3f82-11ea-9177-bc24c0c69a5a.png)

It doesn't seem to be working. No new collection is created.

**Comment by liyasthomas** [comment]
That option is for Postwoman Collections.

**Comment by AdityaAnand1** [comment]
Strongly recommend re-opening.

Just as an example (my use-case): There are a few things stopping me from using postwoman, the second biggest one is the fact that I already have 10+ collection with on average 20+ requests in each collection on Postman (the biggest one is teams). So, the prospect of manually re-inputting all of my 200 requests is daunting enough that I'll probably never get around to it. However, if it was one-click it would be really enticing for me (and I imagine most postman users to give this a shot, likely correlating with a direct spike in the usage and popularity of postwoman as an alternative)

Should be relatively straightforward to dig into postman collection export format as they export it in a human-readable way and even encourage applications (like testing) to be built on top of it since it's so simple. 😄

**Comment by liyasthomas** [comment]
Considering the backward compatibility for this feature, I think its not possible to implement "Postman' s collection import" feature. I'll investigate more into this and already synced Collections and its practical integration.

**Comment by kittiphan2405** [comment]
ในข้อความดังต้นนัน.. ทีมgoogle ได้ตัดสินใจเอาเพราะมีการเข้าระบบบันชีจริง..
จับได้คือสองจุด... จะให้ตอบบไหนอีก.. สนุกเหรอหัวเราะ

กิตติพันธ์

ในวันที่ อา. 9 ก.พ. 2020 12:29 น. Liyas Thomas <notifications@github.com>
เขียนว่า:

**Comment by AdityaAnand1** [comment]
How about a simple one-to-one converter for postman collection format to postwoman collection format?

Input a postman collection, it internally reformats it to the same format as a normal postwoman collection and then uses that.

To lower the effort required when dealing with backward compatibility, perhaps picking only one format version (say, only the current latest v2.1 postman collection format can be imported to postwoman) should make it easier, since v2.1 collection schema will never change (as Postman follows semver for collection versions).

**Comment by JacobAnavisca** [comment]
Just created a PR for this https://github.com/liyasthomas/postwoman/pull/574 and also added an import check

**Comment by liyasthomas** [comment]
Resolved in #574 huge thanks to @JacobAnavisca 

Postwoman now supports importing [Postman Collections `v2.1.0`](https://schema.getpostman.com/json/collection/latest/docs/index.html)

**Comment by allthesignals** [comment]
How do you use this?

**Comment by liyasthomas** [comment]
@allthesignals 
Navigate to Collection tab on right side bar.
Click "Import/Export"
Click "Import from JSON"
Select any Postman_collection.json file

**Comment by mahoriR** [comment]
I really want to try postwoman as a replacement to postman but inability to import postman collection is a deal breaker. This is the console log on chrome-
```
Uncaught TypeError: Cannot read property 'folders' of undefined
    at f.parsePostmanCollection (d598b93aaba4329b6520.js:1)
    at f.parsePostmanCollection (d598b93aaba4329b6520.js:1)
    at FileReader.t.onload (d598b93aaba4329b6520.js:1)
parsePostmanCollection @ d598b93aaba4329b6520.js:1
parsePostmanCollection @ d598b93aaba4329b6520.js:1
t.onload @ d598b93aaba4329b6520.js:1
load (async)
importFromJSON @ d598b93aaba4329b6520.js:1
Qt @ 557011e92a0d7fd3749c.js:2
n @ 557011e92a0d7fd3749c.js:2
c._wrapper @ 557011e92a0d7fd3749c.js:2
```

**Note**: I'm able to import the same collection in insomnia.

**Comment by liyasthomas** [comment]
It's a known issue that Importing Postman Collections fails on nested Collections.
Kindly track this issue: https://github.com/liyasthomas/postwoman/issues/850

**Comment by hyfydistro** [comment]
Is it possible to export for postman?

**Comment by AndrewBastin** [comment]
@hyfydistro not yet, but there is an open issue for this. Follow #2092 for tracking implementation.
