### ISSUE TITLE
i18n support

### ISSUE THREAD

**Issue by FatDoge** [liyasthomas/postwoman#348]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Support multiple languages is user-friendly.
Maybe we can create serveral language profiles and everyone can take a part in the translation plan.

**Comment by liyasthomas** [comment]
This is gold. I was waiting for someone to ask about it. Internationalization should be the next best thing that could happen to PW.

**Comment by FatDoge** [comment]
Thanks again for this awesome project, I think everyone would be pleasure to help with supporting i18n.

**Comment by liyasthomas** [comment]
#351 fixes this. Which is just an initial model. And we're gonna need contributors for finishing it.

**Comment by liyasthomas** [comment]
This was solved in #351 hence closing

**Comment by liyasthomas** [comment]
For those who are interested in localisation, can contribute to i18n branch. i18n is on a seperate branch: https://github.com/liyasthomas/postwoman/tree/i18n and will merge to master once or twice in a week for easy convenience. Please make PRs to i18n branch only so that we could track it's progress easily.
