### ISSUE TITLE
Proxy CORS issue

### ISSUE THREAD

**Issue by AtomicNicos** [liyasthomas/postwoman#365]
**Describe the bug**
Cannot use proxy 

**To Reproduce**
Activate default proxy, launch request.

**Expected behavior**
Request should work.

**Result**
`Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur https://postwoman.apollotv.xyz/. Raison : l’en-tête CORS « Access-Control-Allow-Origin » est manquant.` (CORS policy issue)

Error: "Network Error"
    NuxtJS 2
        exports
        onerror

**Desktop (please complete the following information):**
 - OS: WIN10
 - Browser: Firefox
 - Version: latest

**Additional context**
Bug hunting as promised 😆

**Comment by liyasthomas** [comment]
There's no problem here. I can't reproduce the bug.

**Comment by NBTX** [comment]
Whilst I do know French, errors and error reports in English would be appreciated!

I have not been able to reproduce the error myself, however I'm noticing that this bug was reported 5 hours ago, almost precisely the time that I briefly took down the Apollo server for some brief maintenance.

Could you please test again now and let us know if the situation is resolved?

**Comment by andreujuanc** [comment]
Issue is that if your API must allow request with this header: `Origin: https://postwoman.io`
Or, you can just get repo and run it locally. :)
