### ISSUE TITLE
Intent to translate

### ISSUE THREAD

**Issue by adlpaf** [liyasthomas/postwoman#367]
#Intent to translate to Spanish

I want to translate the lang/es-ES.js

**Comment by liyasthomas** [comment]
Checklist:

- [ ] **Pull the latest changes from `i18n` branch**
- [ ] Find `lang/<<your_file>>.js`
- [ ] **Replace existing dummy translations** with actual translated lacale (no need to update `nuxt.config.js` since language is already added once)
- [ ] Save changes, Commit changes, **Push to `i18n` branch only**

Refer English translation file https://github.com/liyasthomas/postwoman/blob/i18n/lang/en-US.js for reference and stylings. Ping me for any doubts.
