### ISSUE TITLE
Not Working in IE 11

### ISSUE THREAD

**Issue by edisonaugusthy** [liyasthomas/postwoman#37]
**Describe the bug**
App Crashes in  IE 11

**To Reproduce**
1. Open Site in IE11
2. See error

**Expected behavior**
the view should be the same as in chrome.

**Screenshots**
![image](https://user-images.githubusercontent.com/22213856/63592117-72b65e80-c5ce-11e9-9e6c-9ad0346a3713.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser : IE
 - Version 11

**Comment by liyasthomas** [comment]
I afraid IE 11 lackes ES6 support. And thus broke the app. I regret the convince caused. Let me do some more tests and will let you know

**Comment by AndrewBastin** [comment]
Thanks for opening the issue...

I am pretty sure this can be resolved by resolving #31 .

Until then it's impractical to work on IE support while dropping all the niceties of modern JavaScript.

**Comment by diego81b** [comment]
Yeah, vue-cli comes with babel transpiling (more or less @AndrewBastin the same happens in create-react-app).

For working with IE11 we have to pay attention with modern CSS too (for example flex, but there are many others) so question is if we really want the project "IE11 compliant".

Personally i don't find any reason to make it 100% compatible with IE11 also due to the fact that Chrome, Brave and Firefox are free to use browsers for any OS

**Comment by AndrewBastin** [comment]
> Yeah, vue-cli comes with babel transpiling (more or less @AndrewBastin the same happens in create-react-app).
> 
> For working with IE11 we have to pay attention with modern CSS too (for example flex, but there are many others) so question is if we really want the project "IE11 compliant".
> 
> Personally i don't find any reason to make it 100% compatible with IE11 also due to the fact that Chrome, Brave and Firefox are free to use browsers for any OS

@diego81b yeah, well the issue opened here is that the app doesn't work on IE11, lending some basic support doesn't hurt.

I don't think we need full IE11 compliance, because that will make it difficult or limit the stuff we can do with this app, but some graceful fallbacks will be nice.

Well, another kinda being a wrench to this is that I am kinda working on making Postwoman kinda run as a lightweight cross-platform native desktop app (still by not using Electron) instead by depending on system webviews, in Windows that will be IE, so well, I kinda would love 100% IE compliance :sweat_smile:

**Comment by liyasthomas** [comment]
Closing the issue since #51 solved it
