### ISSUE TITLE
request on website

### ISSUE THREAD

**Issue by KJohn2q** [liyasthomas/postwoman#385]
I pull request on website (https://postwoman.io/),but always  get response failed.It runs on postman client.I don't know if I dp some wrong thing.I wish get some help.Thank  you.
![图片](https://user-images.githubusercontent.com/20499046/69908301-6473ac00-1421-11ea-8c83-7ec782ad183e.png)
![图片](https://user-images.githubusercontent.com/20499046/69908306-75242200-1421-11ea-9151-4feb8e2d5761.png)

**Comment by AndrewBastin** [comment]
Hi there,

Thanks for using Postwoman ❤️

Your issue can be resolved by either changing the URL field from `http://httpbin.org` to `https://httpbin.org` or you can activate the Proxy from the Settings tab.


Have a nice day! 😄

**Comment by KJohn2q** [comment]
Hi there,

I'm glad for your anser.I have other question I confused.

* Why I use http on postwoman website not work, but it works on postman?
* What about local domain?
* What about other public domain that only maintain http?

I'm sorry to bother you,and I don't some  explain on other place.The project don't have complete docs.

**Comment by liyasthomas** [comment]
1. The very website `postwoman.io` is hosted on a HTTPS protocol. This means all requests are allowed for only HTTPS site by default. This ia a security feature implemented in browsers.

We've Proxy mode. This allows you to access HTTP endpoints from postwoman.io. Toggle Proxy mode from https://postwoman.io/settings

HTTP is non-secured and allows vulnerabilities.

In Postman they automatically route non-HTTPS request to proxy without our permission.

2. `localhost` is currently not supported since access to localhost is restricted to websites. This could be tackled by our upcoming native build. Track it's progress on: #267 

3. All non-HTTP domains can be accessed from Proxy mode.

**Comment by KJohn2q** [comment]
I'm glad for your anser.I don't have other question temporally,so you can close this issue.

If I have other question during use postwoman,I will back. 

Thank you!
