### ISSUE TITLE
IE Support

### ISSUE THREAD

**Issue by AndrewBastin** [liyasthomas/postwoman#386]
**Is your feature request related to a problem? Please describe.**
Postwoman is broken in Internet Explorer (tested in IE11)

**Describe the solution you'd like**
Postwoman should work properly in IE

**Describe alternatives you've considered**
Not Applicable

**Additional context**
This feature is crucial for the implementation of the native wrapper ( #267 )

**Comment by liyasthomas** [comment]
I'll work on it.

**Comment by liyasthomas** [comment]
Babel transpiled build throws `syntax error`.
But at least I was able to get Nuxt error page! I've hope.

**Comment by NBTX** [comment]
@liyasthomas have you tried transpiling to an older destination in babel?

**Comment by liyasthomas** [comment]
Nope. I went with the latest version. But i dont think babel os the reason, I think it's an issue with template literals etc.

**Comment by NBTX** [comment]
@liyasthomas yeah You actually want to select an older destination version - if you make it target internet explorer and other older browsers, Babel will polyfill missing features such as template literals (which IE doesn't support)

**Comment by liyasthomas** [comment]
Okay, will try with a lower version and let you know.

**Comment by AndrewBastin** [comment]
Sooo, any updates ?

**Comment by mabushey** [comment]
Who runs IE? What a joke. I hope the Postwoman codebase is not cluttered with hacks to "fix" this.

**Comment by liyasthomas** [comment]
IE support is mainly required for offline build which is a WIP.

**Comment by AndrewBastin** [comment]
@mabushey Thank you for voicing your concerns, and yes no one practically uses IE, especially in our target audience. But we do need IE support to implement a lightweight native client solution for Postwoman.

I am trying my best to not pollute the codebase for IE support, most of the work needed for IE support is just optionally loading separate scripts for implementing the missing behaviors in IE and to ensure the generated Postwoman code is suitable for IE. None of the changes introduced/proposed so far has brought changes to the main Postwoman code.

I usually also discuss the changes I bring before I work on them on Telegram/Discord.

**Comment by NBTX** [comment]
@mabushey I can confirm - on account of IE support not even being present - that nobody who uses postwoman does so with IE.

The reason we're even considering IE support is that we need some way to get around CORS restrictions. Postman got around this with electron, though we've found it to be bulky and slow - plus it's got all of Chromium's notorious memory issues.

Thus, in order to avoid using electron, @AndrewBastin was trying to build a native version that simply used whatever browser rendering engine came on the OS by default. Sadly, on Windows, that's still Internet Explorer - even in the latest versions of Windows 10. Hence, we have been investigating and trying to implement IE support.

I do feel that as our biggest user audience is most likely on Windows, we should avoid IE at all costs given it would be, frankly, a second-rate experience not to mention that the browser is essentially put on the back-burner by Microsoft. Hence, my preferred solution is to use a proxy server which would avoid this problem, though it remains to be seen how usable the proxy is.

(You can see some details of how the proxy would be implemented here) https://github.com/liyasthomas/postwoman/issues/267#issuecomment-567904336

**Comment by liyasthomas** [comment]
I think this issue is stale now and should be closed. @AndrewBastin what do you say?

**Comment by AndrewBastin** [comment]
Yeah sure, I don't think IE support is something that is in immediate need. Or actually in a need ever at all :sweat_smile: (thank god)
