### ISSUE TITLE
Save to collections after deleting all the collections causes an error page

### ISSUE THREAD

**Issue by aksappy** [liyasthomas/postwoman#390]
**Describe the bug**
When trying to save to collection, after deleting all the existing collection throws 

> this.$store.state.postwoman.collections[this.$data.requestData.collectionIndex] is undefined

**To Reproduce**
1. Save a request to an existing collection.
2. Delete all the existing collections
3. Click on Save to Collections
4. Error is seen, in addition to that neither "Go Home" or "Reload" does not work.

**Expected behavior**
Either say that there is no collection OR Save without a collection OR prompt for new collection

**Screenshots**

![image](https://user-images.githubusercontent.com/4348461/69923956-73d11480-1476-11ea-8c93-596f65e311de.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 
 - 70.0.1

**Comment by adevr** [comment]
I'm checking out this bug, and I detected that some array validation was missing.

Maybe this should be fixed with the recreation of a default collection "My Collection", in background or with a modal showing on the page, with the collection creation form. 

What do you guys think is the best solution?

**Comment by adevr** [comment]
@liyasthomas Implemented this validation, to prevent this bug from happenning..
Launching PR.

![imagem](https://user-images.githubusercontent.com/36900578/70397949-684d9280-1a0e-11ea-81ac-b232ed61fb9b.png)
