### ISSUE TITLE
Raw input disabled is not working properly

### ISSUE THREAD

**Issue by elangovanshanthi** [liyasthomas/postwoman#394]
**Describe the bug**
Raw input disabled is not working properly

**To Reproduce**
1. To make the api request by using POST methods via RAW INPUT.
2. Checking the POST api results, it should works as expected.
3. Now disable the RAW INPUT and will make the GET Request.
4. Still RAW INPUTS are passing in GET methods and even if RAW INPUTS disabled also. 
Please fix this issue.

**Expected behavior**
If RAW INPUTS is disabled, it should not pass in API request

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Ubuntu16.04]
 - Browser [Chrome]
 - Version []

**Comment by liyasthomas** [comment]
> Still RAW INPUTS are passing in GET methods and even if RAW INPUTS disabled also.
Please fix this issue.

I couldn't reproduce this issue. GET doesn't pass raw payload in request.

**Comment by elangovanshanthi** [comment]
@liyasthomas can you tried the above reproduce steps.

It is simple ,
you add some raw data in POST method and just on/off the raw input after that you will change method as GET method, now you will check above request parmas.

**Comment by liyasthomas** [comment]
That's a feature. Actually when you disable the raw input or changed to any other `method`, payload is stored to the app's state so it could be used next time.

Think of this as: You send a POST request with some payload and have to check it's GET response. So you switched to GET and send another request. Now, if we clear the POST payload, you've to again type in all payload again since it's not in app's memory. This is why payload is preserved for using next time.

Don't worry GET request won't send payload. It's just save in your localStorage.
