### ISSUE TITLE
Custom request method

### ISSUE THREAD

**Issue by JanoschDeurer** [liyasthomas/postwoman#398]
**Is your feature request related to a problem? Please describe.**
Some APIs use custom request methods. For example the API of vault uses `LIST` do deliver secrets:
https://www.vaultproject.io/api/secret/kv/kv-v2.html#list-secrets

**Describe the solution you'd like**
It would be great to have a custom option that opens a text field where one can put in strings that describe the method.

Another solution is to just replace the dropdown with a text field.

**Describe alternatives you've considered**
I think for such APIs the only alternative is to use a different tool, but I really like postwoman :)

**Comment by liyasthomas** [comment]
Will try to implement them.

**Comment by liyasthomas** [comment]
`method` list have been adapted from https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods and since `LIST` is not an officially safe method, we can't list that in our default set of methods. But we've implemented an `<input>` box instead of `<select>` options, this allows user to type in any custom `method` they want. These custom methods could be used in endpoints that support those methods.

**Comment by liyasthomas** [comment]
@JanoschDeurer can you do a quick verification of custom method feature?

Check out https://deploy-preview-400--postwoman.netlify.com and try out few custom methods you're family of.

Don't forget to use the endpoints that do support those methods. The default one doesn't seems to have support for custom methods.

**Comment by JanoschDeurer** [comment]
Wow, that was fast 🤩, thank you so much. I tested it with a few of the custom methods that vault uses and it works.

**Comment by liyasthomas** [comment]
Shoor suggestions and along with PRs 😌👍
