### ISSUE TITLE
Serialize a request into JSON?

### ISSUE THREAD

**Issue by banezaklan** [liyasthomas/postwoman#4]
Hey there, have you already planned for serializing entire request into JSON? I'm looking for a simple way to document a REST API, and make it "interactable" in the same time.
Like postman has these "Collections" but simpler I think...

**Comment by AndrewBastin** [comment]
Hey....

That seems dope, I will work on a PR for that...

**Comment by AndrewBastin** [comment]
@brandonros I like this suggestion, can you open this as a separate issue ?

I will start working on this PR.

**Comment by NBTX** [comment]
The problem with that though is that the state would, for some more advanced queries be massive.

**Comment by AndrewBastin** [comment]
> The problem with that though is that the state would, for some more advanced queries be massive.

We can introduce support for basic queries only (ie method, url, path) for now.

I think that would still be pretty helpful.

We could flush it out as we go...

**Comment by liyasthomas** [comment]
Appending on hash or query string of the URL is the easiest way to do this, but in a long run, this would be painful. But as @brandonros said, this could be the easiest way to sahe it to others with copy/paste.

Alternate option is export and import. Which solves the case of complex or large queries but need further dependencies I suppose.

**Comment by jgroom33** [comment]
postman uses the concept of environment to store state.  this works ok, but is limited because it is a string by default.
the cache should be a combination of responses, requests, and user defined vars
The UI should present each of these objects.
To reference any of these objects, a templating engine should be implemented. This would allow the following behavior:

1. define a var of: foo={"model":{"foo":"bar"}}
2. use var in a request: https://postwoman.foo/?state={{foo}}
3. use response in subsequent request: https://postwoman.foo/blog/{{request1label.response.items[0].id}}

**Comment by TheHollidayInn** [comment]
I think that with my new collections PR, I could solve this issue since the requests are stored in vuex now. I could add a copy button to the requests that are saved and allow the user to get the json

**Comment by liyasthomas** [comment]
#176 #209 fixes this. Hence closing.
