### ISSUE TITLE
Request Headers

### ISSUE THREAD

**Issue by JockDaRock** [liyasthomas/postwoman#57]
**Is your feature request related to a problem? Please describe.**
Would like to be able to add custom request headers to requests before sending and control headers that are sent.

**Describe the solution you'd like**
A section the has request headers where you can control and add headers to be sent with API request

**Comment by liyasthomas** [comment]
That would be great. Lets discuss its scope here and will try to implement it.

**Comment by brandonros** [comment]
One of my biggest gripes with Postman is how it tries to handle the `Cookie` header for you (based off of the Set-Cookie response)

It tries to blend its own internal cookie jar with a sometimes explicitly set Cookie header.

I'd say, make the cookie jar functionality an option, therefore allowing the user to "break out" and handle the Cookie header on their own, if needed.

**Comment by brandonros** [comment]
Scope:

UI presents the same UI for "parameters" to manage key value pairs of string (headerName) -> string (header value). Pass them along as request header. Voila. 🎉 

Where it gets tricky is.... do you want to support cases where the "key" is not unique? example:

`curl -H 'foo: 1' -H 'foo: 2'`

I don't know why people would ever do this, but I know for darn sure that TypeScript complains if I try to treat a request header in node.js as a string instead of `string | string[]`.

**Comment by liyasthomas** [comment]
#68 fixes this issue hence closing
