### ISSUE TITLE
Bigger URL and/or Path input field

### ISSUE THREAD

**Issue by geongeorge** [liyasthomas/postwoman#581]
I'm working on a project and I'm dealing with similar URLs of an API.
Postwoman only provides a small input field to add in the URL

![image](https://user-images.githubusercontent.com/29296982/74955841-3ce21d80-542b-11ea-97e0-de6686a68970.png)

I cannot properly see what URL I'm sending the request to.

Even the history section shows a small excerpt of the entire URL.

### Possible Solution

This is what postman does when thrown a big URL

![image](https://user-images.githubusercontent.com/29296982/74956070-8cc0e480-542b-11ea-99fe-624fec086655.png)

**Comment by liyasthomas** [comment]
Thanks for the suggestion, will update UI to support larger URLs.

**Comment by its-tayo** [comment]
Hi @liyasthomas can I work on this please?

**Comment by liyasthomas** [comment]
@its-tayo hi there! You're free to work on this :tada:

**Comment by AndrewBastin** [comment]
@liyasthomas @its-tayo 

I think the best implementation for the URL field is that we can have it be like it can collapse into one field, without needing separate URL and Path fields (I usually only use the URL field, mostly because I usually copy paste URLs).

In case the user needs the split view, we can have a sorta a collapsible thingy, to like expand the URL input into the separate Host and Path fields.

Again, it's just an opinion and it will need some effort to be implemented properly and presented cleanly.

**Comment by its-tayo** [comment]
Hi, @liyasthomas I'm sorry I wouldn't be able to work on this, I thought this project was built with React.
