### ISSUE TITLE
Add setting to disable scroll animations

### ISSUE THREAD

**Issue by dmitryyankowski** [liyasthomas/postwoman#592]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would like the ability to disable the scroll animation. For example when I use the GraphQL feature of the site and click `Get Schema` and the play button `Run Query`, it auto scrolls (**which I personally don't like**). It would be nice to have a setting to disable this :)

**Describe alternatives you've considered**
As there is already a settings section. It could be added to the settings tab!

**Additional context**

@liyasthomas

**Comment by AndrewBastin** [comment]
@dmitryyankowski I handle the GraphQL section of Postwoman.


So, like do you want to disable the smooth autoscroll animation or just disable autoscrolling alltogether

**Comment by dmitryyankowski** [comment]
I'd like to disable autoscrolling all together @AndrewBastin :)

**Comment by AndrewBastin** [comment]
Well, I will tackle this issue on Tuesday. Because I am currently a bit busy with the GraphQL features, and the auto scrolling stuff is a general feature.

It seems to be a pretty easy issue to tackle for beginners.
So, if anyone wants to tackle this by Tuesday. Please do (although, don't forget to report here, so other people will know you are tackling this issue).

**Comment by dmitryyankowski** [comment]
Going to try and add this today for you @AndrewBastin I think I can handle it :)

**Comment by AndrewBastin** [comment]
Cool, have fun!

Assigning this issue to you.
