### ISSUE TITLE
Comparison with Postman is missing

### ISSUE THREAD

**Issue by nskazki** [liyasthomas/postwoman#69]
A comparison with the obvious competitor is must-have for this repository, especially taking into account that you're referencing to it in the name of your app :)

**Comment by liyasthomas** [comment]
Let me make this clear once and for all.

The reason why Postwoman has born is because my 7 year old PC won't run Postman. I asked my friends who've used Postman and they made it clear that it had high CPU usage, high RAM consumption and had annoying popups. It used to take 7-30 seconds to initiate the app. It has even crashed some systems. I won't wonder because I've prior experience in developing and using Electron apps and had same situations by myself.

But at the end of the, I need to test my APIs. That's why I made Postwoman. I don't see Postman as a competitor since Postman is a totally different kind of product. Even though both does the same thing, the implementations are totally different.

Postwoman is a PWA. It's lightweight, faster, efficient and runs on any platform, any device, along with other tones of features. Moreover it's an open sourced, fully transparent, free service. Unlike Postman, there are several things only Postwoman can do. Developers can suggest, contribute and make things better in Postwoman.

(I'll be updating this thread later with links, proofs and testimonials from real users of both apps)

**Comment by NBTX** [comment]
@liyasthomas Perhaps it is worth adding that to the README?
