### ISSUE TITLE
Error: Network Error. Check console for details

### ISSUE THREAD

**Issue by CNzhou97** [liyasthomas/postwoman#704]
**Describe the bug**

**To Reproduce**
1. Open Postwoman
2. Click on Send
3. Scroll down to console

**Expected behavior**
response OK

**Screenshots**
![image](https://user-images.githubusercontent.com/31788525/77426905-68806b00-6e10-11ea-9e3b-b18c1f1d8c15.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser chrome, safari
 - Version 79.0.3945.117

**Comment by liyasthomas** [comment]
If your endpoint is in `localhost`, please install official extensions to support `localhost` endpoints.

**Comment by CNzhou97** [comment]
It's the same effect if I use ip
![image](https://user-images.githubusercontent.com/31788525/77427876-1e988480-6e12-11ea-99af-d521f2c4ba70.png)

**Comment by liyasthomas** [comment]
Are you sure the requested endpoint have CROS disabled?

**Comment by Slaviusz** [comment]
Can we reopen this? I have the same issue, with/without the extension. I cannot open any connection to localhost.

**Comment by liyasthomas** [comment]
@AndrewBastin

**Comment by Slaviusz** [comment]
Thanks. 
Basically, my symptoms are exactly the same. Trying to call rest API endpoint on localhost results in :

`Access to XMLHttpRequest at 'http://127.0.0.1:9000/api/auth/login' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

I tried installing the extension and also including the URL into unsafely-treat-insecure-origin-as-secure origins to no avail.

Thanks for help.

**Comment by liyasthomas** [comment]
Please check these hotfixes:
1. Check you've installed the latest version of browser extension. Kindly go through the extension's link (in readme) and verify the installed version number.
2. Check Postwoman is allowed to use extensions. Navigate to Settings > Extensions section. Make sure "Use extension" toggle switch is turned on.
3. Check endpoints don't have CROS restrictions.

**Comment by Slaviusz** [comment]
1. compiled Postwoman 30 minutes ago from latest git commit. Installed the extension 15 minutes ago from official link provided within Postwoman. The version reported is 0.5. I also tried manual update in browser's extensions config page.
2. Extension is allowed, active and configured with access to URLs and in Incognito.
3. CORS is NOT enabled on this app (I'm the developer)

However when I explicitly enabled CORS with Access-Control-Allow-Origin: * everything works now. Is it now enforced that the host MUST enable CORS otherwise the behavior is equal to invalid origin?

**Comment by liyasthomas** [comment]
If that's the case, we'll have to look further into it. Huge thanks for the debugging and reporting the issue.

**Comment by Slaviusz** [comment]
You're welcome. Thanks for having a look.

**Comment by AndrewBastin** [comment]
Hi there, 

Sorry for the late response, I am really swamped with personal stuff and end of the semester university work.

Due to security concerns of allowing open access to the extension hooks, the Postwoman Extension only hooks into the following domains

```
http(s)://postwoman.io/
http(s)://postwoman.netlify.com/
```

If you are using localhost, you will need to make your own build of the extension (more info on that [here](https://github.com/AndrewBastin/postwoman-extension)) with the permissions activated for your localhost page in the manifest.


Thanks for using Postwoman ❤️

**Comment by liuxueyiTest** [comment]
> 3\. Check endpoints don't have CROS restrictions

how to do ?

**Comment by liyasthomas** [comment]
> > 3. Check endpoints don't have CROS restrictions
> 
> how to do ?

[`CORS`](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) is a security mechanism imposed on API endpoints. Its easily discoverable from the developers side. You can simple try hitting the endpoint from Hoppscotch.io and if there's no issue, and you got `Okay 200` response, then it doesn't have CORS. If API response got any error, check console to know where it's due to CORS restrictions. You can fix CORS issues with Hoppscotch Extension.

**Comment by liuxueyiTest** [comment]
&nbsp;thank you very much.
Could&nbsp;you tell me how to turn off the cros ？I am is tester。&nbsp;I would appreciate it if you could give me some advice at your convenience.
&nbsp;
------------------&nbsp;Original&nbsp;------------------

**Comment by liyasthomas** [comment]
https://stackoverflow.com/questions/3102819/disable-same-origin-policy-in-chrome

**Comment by liuxueyiTest** [comment]
Thank you very much for your help.Hoppscotch is installed to my local computer, which is the same computer as my browser.According to your information, There is something wrong with my Browser extension.
&nbsp;
&nbsp;














------------------ Original ------------------

**Comment by liuxueyiTest** [comment]
Why can't My self-installed server show Extension Version.&nbsp;Could you please tell me where I am wrong? If you are convenient, please guide me.


&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: &nbsp;"刘学义"<liuxueyi@xsyxsc.com&gt;;
Date: &nbsp;Fri, Dec 4, 2020 07:21 PM
To: &nbsp;"hoppscotch/hoppscotch"<reply@reply.github.com&gt;; 

Subject: &nbsp;Re: [hoppscotch/hoppscotch] Error: Network Error. Check console for details (#704)

&nbsp;

Thank you very much for your help.Hoppscotch is installed to my local computer, which is the same computer as my browser.According to your information, There is something wrong with my Browser extension.
&nbsp;
&nbsp;














------------------ Original ------------------

**Comment by liuxueyiTest** [comment]
如果我访问我本地的自己部署的 hoppscotch 意思我要自己弄个浏览器扩展。
