### ISSUE TITLE
Improve contrast of UI components in all themes

### ISSUE THREAD

**Issue by jahirfiquitiva** [liyasthomas/postwoman#819]
Hello

I'm having a hard time trying to pick a theme because none of them is easy enough for me.

It's hard for me to differentiate between background, container and field colors, because they almost look the same for me.

I'd appreciate if you improved that or added some borders or something that could help differentiate them.

Thanks in advance

**Comment by liyasthomas** [comment]
The current themes are revised by the community over the past few months for better readability - but we're open for suggestions. Kindly go through https://github.com/liyasthomas/postwoman/blob/master/assets/css/themes.scss and perhaps contribute a PR to fix current issues you're having regarding the contrast?

since this is not an issue regarding the core functionalities - I'm closing it.
