### ISSUE TITLE
Postwoman Docker Container behind Reverse Proxy

### ISSUE THREAD

**Issue by woigl** [liyasthomas/postwoman#906]
We want to use the Postwoman Docker container begin an NGINX reverse proxy with a subpath i.e. http://hostname/postwoman

This is an extract of the NGINX config:
```
location /postwoman/ {
  proxy_pass http://postwoman:3000/;
  proxy_set_header Host $host;
}
```

We would expect that the reverse proxy path would be used for the requests, but it seems not to work.
See this image:
![Postwoman-Rever-Proxy-Issue](https://user-images.githubusercontent.com/17859431/83031293-6ec7d900-a045-11ea-8f49-5694a829102e.png)

We are using the Docker Image v1.9.7.

How can we solve this?

**Comment by liyasthomas** [comment]
@JanoschDeurer can you help me to resolve this issue?

**Comment by JanoschDeurer** [comment]
@liyasthomas Yes, i'll give it a look later today

**Comment by JanoschDeurer** [comment]
I wrote a small test setup and got the same errors.

This doesn't look like a Docker problem to me. I'm not really good with web development, but it looks to me like the paths to the .js files in the head section of the index.html should be relative links instead of absolute ones. @liyasthomas if you give me a hint where these links are generated I'll test it.

Here is my test setup:
```
$ cat docker-compose.yml
version: '3.7'
services:
  postwoman:
    image: liyasthomas/postwoman:v1.9.7
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
```

```
cat nginx.conf
events {
  worker_connections  4096;  ## Default: 1024
}

http {
  server { # simple reverse-proxy
    listen       80;
    location /postwoman {
      proxy_pass      http://postwoman:3000;
    }
  }
}
```

**Comment by AndrewBastin** [comment]
The `index.html` file is generated by the Nuxt build process and there is no way currently to make Nuxt generate relative URLs (see issue https://github.com/nuxt/nuxt.js/issues/1380).

If you are using subpaths, I am pretty sure you can override the [`router.base`](https://nuxtjs.org/api/configuration-router#base) to generate code based on the subpath.

**Comment by JanoschDeurer** [comment]
I looked into the `nuxt.config.js` file and it seems there is already an evn variable that does exactly what we need:
https://github.com/liyasthomas/postwoman/blob/master/nuxt.config.js#L17
But I think this is only triggered on build time right?

**Comment by liyasthomas** [comment]
@JanoschDeurer yes you're right - it's only triggered at the build time.

**Comment by JanoschDeurer** [comment]
What we can do is add an env variable and then one has to set it in the Dockerfile or pass it to docker build with
```
docker build --build-arg BASE_PATH=/postwoman
```
However, I can't get this to work in my local setup, maybe the line I referenced above is not the right one, because I changed that variable and it didn't have any effect for me.

**Comment by liyasthomas** [comment]
@woigl change the `router.base` value to your desired subpath in https://github.com/liyasthomas/postwoman/blob/master/nuxt.config.js
ie: to serve image in `/pw` subpath, make the following change:

```
export const routerBase =
  process.env.DEPLOY_ENV === "GH_PAGES"
    ? {
        router: {
          base: `/${repoName}/`,
        },
      }
    : {
        router: {
          base: "/pw", // 👈 desired subpath
        },
      }
```

for convenience, you can set:

```
base: process.env.BASE_PATH
```

and pass it to docker build with:

```
docker build --build-arg BASE_PATH=/postwoman
```

**Comment by woigl** [comment]
@liyasthomas does this mean, that we have to make a full build or just a build based on your image?

Can you provide me a sample Dockerfile?

**Comment by liyasthomas** [comment]
Build have to tweaked on nuxt.config.js file. Current docker file works good.

**Comment by JanoschDeurer** [comment]
@woigl you can set an environment variable in the Dockerfile by adding:
```
ENV BASE_PATH=/postwoman
```
to your Dockerfile.
If you want to set the variable with:
```
docker build --build-arg BASE_PATH=/postwoman
```
use `ARG` instead:
```
ARG BASE_PATH=/postwoman
```
In any case you always have to run a `docker build` when you change the path. And to your question, yes this build has to be for the container in this project, not one that is based on it.

I know this was not your question, but in my personal experience it is often a lot easier to use subdomains instead of path based routing, also I can recommend using [traefik](https://containo.us/traefik/) as a reverse proxy, it has a really nice docker integration and it handles LetsEncrypt for you.

**Comment by JanoschDeurer** [comment]
@W1M0R you can't really. Setting the path variable must happen before `npm build` is run. Maybe you can run the build step again, but I think it would make more sense to just alter the Dockerfile in this project for your purposes.

**Comment by e-mikh** [comment]
any update on this with current version? still possible?
